fix metrics api not found
apache/celeborn pull request #2764
Opened 2024-09-25 18:32 UTC by turboFei

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2024-09-26 06:29 UTC, FMX approved these changes
LGTM. I think this change has no side effects.

2024-09-26 08:30 UTC, cxzl25 approved these changes

2024-09-27 08:07 UTC, FMX commented
After some digging,  this PR might not find the root cause.  The master class is a subclass of the Service class.
The master object creates a master instance and calls its initialize method.
<img width="587" alt="截屏2024-09-27 16 04 03" src="https://github.com/user-attachments/assets/574f994f-0c5b-4db3-a1bd-79349fc4dd9c">
Master instance calls its superclass method of initialize.
<img width="534" alt="截屏2024-09-27 16 04 44" src="https://github.com/user-attachments/assets/0585f14d-02e1-4494-8443-3b4cee2a1423">
HttpService calls its superclass method of initialize.
<img width="477" alt="截屏2024-09-27 16 05 27" src="https://github.com/user-attachments/assets/00f1609f-11ed-4a87-b180-204544e57269">

Those initialization methods are invoked in the same thread.

We should find out the root cause and fix this problem.

2024-09-27 08:08 UTC, FMX requested changes
Maybe find out the root cause for this problem will be better.

2024-10-01 21:54 UTC, turboFei commented
Hi @waitinfuture 

I have changed the PR description and title.

Just start to expose the RESTful server after all handlers initialization finished.

2024-10-09 01:27 UTC, RexXiong commented on service/src/main/scala/org/apache/celeborn/server/common/HttpService.scala
> +    httpServer.start()
> how about starting/exposing the http endpoint after all handlers added? @waitinfuture
> 
> In our use case, there is an agent to collect the celeborn metrics periodically.

Sounds reasonable

2024-10-09 01:27 UTC, RexXiong approved these changes
LGTM

2024-10-09 03:35 UTC, closed without merging